spring.application.name=backend-project
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
jwt.secret=bW9qU3VwZXJUYWpuaUtsanVjS29qaU1vcmFCaXRpRG92b2xqbm9EdWdhY2FrMTIzNDU2

